global using System;
global using System.Linq;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using System.Runtime.Versioning;
global using Blazonia.Core;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.DependencyInjection;
global using Avalonia;
// global using ACP = Avalonia.Controls.Primitives;
global using Blazonia;
global using Blazonia.Extensions;