parameters:
  windowsPool: VSEng-MicroBuildVS2019

jobs:
- job: Windows
  pool: ${{ parameters.windowsPool }}
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml

  - powershell: '& (./azure-pipelines/Get-nbgv.ps1) cloud'
    displayName: Set build number

  - template: dotnet.yml

#- job: Linux
#  pool:
#    vmImage: Ubuntu 16.04
#  steps:
#  - checkout: self
#    clean: true
#  - template: install-dependencies.yml
#  - template: dotnet.yml

#- job: macOS
#  pool:
#    vmImage: macOS 10.13
#  steps:
#  - checkout: self
#    clean: true
#  - template: install-dependencies.yml
#  - template: dotnet.yml

- job: CodeSign
  dependsOn:
  - Windows
 # - Linux
 # - macOS
  pool: ${{ parameters.windowsPool }}
  condition: succeededOrFailed()

  variables:
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: _TeamName
    value:  Emblazon

  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - name: _BuildArgs
      value: /p:TeamName=$(_TeamName)
    - name: _SignType
      value: real

  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    - name: _BuildArgs
      value: ''
    - name: _SignType
      value: test
    - name: _PublishArgs
      value: ''

  steps:
  - task: MicroBuildSigningPlugin@2
    inputs:
      signType: $(_SignType)
      feedSource: 'https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json'
    continueOnError: false
    env:
      TeamName: $(_TeamName)
  - task: MicroBuildCodesignVerify@2
    inputs:
      TargetFolders: '$(Build.StagingDirectory)'
      ExcludeSNVerify: true
  - task: MicroBuildCleanup@1

- job: WrapUp
  dependsOn:
  - CodeSign
  pool: ${{ parameters.windowsPool }}
  condition: succeededOrFailed()
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
    parameters:
      initArgs: -NoRestore
  - template: publish-deployables.yml
